[INFO][2020-08-15 10:50:06,231][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:50:08,257][views.py:32]Accessed /info with showInfo
[INFO][2020-08-15 10:50:09,777][views.py:62]Accessed /list-article with showArticlePage
[INFO][2020-08-15 10:50:25,745][views.py:13]Accessed / with showHome
[INFO][2020-08-15 10:50:27,046][views.py:51]Accessed /login_ with showLogin
[INFO][2020-08-15 10:50:31,401][views.py:74]Accessed /dologin with doLogin
[INFO][2020-08-15 10:50:31,599][views.py:13]Accessed / with showHome
[INFO][2020-08-15 10:50:33,607][views.py:62]Accessed /list-article with showArticlePage
[INFO][2020-08-15 10:51:34,387][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-15 10:51:34,836][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:53:52,281][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-15 10:53:52,713][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:54:50,042][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-15 10:54:50,486][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:55:03,821][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-15 10:55:04,259][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:55:15,372][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-15 10:55:15,817][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:55:23,296][views.py:62]Accessed /list-article with showArticlePage
[INFO][2020-08-15 10:55:45,660][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 10:55:46,179][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:56:06,515][views.py:51]Accessed /login_ with showLogin
[INFO][2020-08-15 10:56:06,524][views.py:13]Accessed / with showHome
[INFO][2020-08-15 10:56:18,048][views.py:62]Accessed /list-article?fid=2 with showArticlePage
[INFO][2020-08-15 10:56:25,585][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[INFO][2020-08-15 10:56:50,150][views.py:13]Accessed / with showHome
[INFO][2020-08-15 10:56:51,745][views.py:51]Accessed /login_ with showLogin
[INFO][2020-08-15 10:56:56,102][views.py:74]Accessed /dologin?hashcode=5328f58ffb2425b2749701f281cbf21f9b776417f06cc35ba4511861a1cc0670&username=root&password=root with doLogin
[INFO][2020-08-15 10:56:56,201][views.py:13]Accessed / with showHome
[INFO][2020-08-15 10:59:11,007][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-15 10:59:11,458][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 10:59:26,971][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-15 10:59:27,422][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 11:00:19,089][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[ERROR][2020-08-15 11:00:27,714][log.py:222]Internal Server Error: /article-3/
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\article\views.py", line 11, in showArticlePage
    logger.info(f'Accessed {request.get_full_path()} with showArticlePage'%(id_))
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:00:46,673][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 11:00:47,134][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 11:00:48,239][views.py:11]Accessed /article-3/ with showArticlePage
[INFO][2020-08-15 11:00:49,456][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:00:49,660][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:00:52,272][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[INFO][2020-08-15 11:01:42,940][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[INFO][2020-08-15 11:01:44,245][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:01:44,295][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[ERROR][2020-08-15 11:03:56,567][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:07:41,973][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:08:04,763][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:08:14,173][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:08:21,429][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:08:22,353][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:09:32,886][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:09:54,686][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:10:13,122][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:11:00,915][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:12:38,111][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:12:38,170][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:13:10,631][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:13:10,686][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:14:28,803][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:14:28,857][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[ERROR][2020-08-15 11:14:33,613][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:14:54,885][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:14:54,941][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:15:05,856][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:15:05,908][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:15:27,138][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:15:27,193][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:15:42,388][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:15:42,442][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:16:00,596][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:16:00,651][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:16:21,537][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:16:21,596][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:18:51,013][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:18:51,072][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:18:58,834][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:18:58,886][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:19:22,694][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:19:22,749][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:22:12,695][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:23:22,478][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:24:53,217][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:25:06,209][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:25:20,338][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:25:33,737][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:25:48,823][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:26:29,162][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:26:49,432][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:26:49,499][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:26:51,243][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:26:51,315][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:26:59,406][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:26:59,469][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:27:36,372][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:27:36,451][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:28:03,975][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:28:04,059][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:28:04,758][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:28:04,822][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:28:24,715][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:28:24,781][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:28:34,973][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:28:35,050][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:28:46,634][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:28:46,707][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:28:52,937][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:28:53,008][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:29:13,637][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:29:13,707][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:29:14,397][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:29:14,461][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:29:22,999][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:29:23,069][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:29:24,396][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:29:24,459][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:29:30,670][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:29:30,740][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:29:54,352][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:29:54,424][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:30:11,717][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:30:11,792][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:30:15,642][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:30:15,708][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:30:29,277][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:30:41,382][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:31:12,056][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:34:46,655][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:34:50,919][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:35:18,268][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 11:35:18,366][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 11:35:32,630][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 11:36:19,424][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 12:17:34,858][autoreload.py:222]D:\Project\webinfo\webinfo\urls.py changed, reloading.
[INFO][2020-08-15 12:17:35,316][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:17:54,065][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:17:54,522][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:18:24,281][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:18:24,752][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:20:34,397][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:20:35,054][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:20:48,387][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:20:48,848][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:20:53,398][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:20:53,874][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:21:03,900][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:21:04,371][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:21:11,044][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:21:11,505][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:21:33,555][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:21:34,009][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:21:47,315][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:21:47,772][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:22:18,685][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:22:19,279][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:22:50,153][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:22:50,627][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:23:13,830][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:23:14,302][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:23:19,905][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-15 12:23:20,373][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 12:23:56,437][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 12:24:03,661][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 17:32:24,445][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 17:32:24,585][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 18:06:24,615][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 18:06:24,700][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 18:06:26,566][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 18:06:26,633][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 18:06:36,302][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 18:06:36,373][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 18:07:02,045][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 18:07:02,936][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 18:07:03,626][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 18:07:04,257][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 18:07:35,760][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 18:07:39,177][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 18:07:41,318][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 18:07:49,506][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 18:07:49,565][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 18:08:03,354][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 18:08:03,431][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 18:08:30,290][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 18:09:19,691][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-15 20:32:42,943][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 20:32:45,543][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 20:33:29,466][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 20:33:29,529][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 20:34:08,068][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 20:34:08,142][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 20:36:04,988][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 20:36:05,065][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 20:36:36,325][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 20:36:36,404][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 20:37:11,254][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 20:37:11,316][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 20:37:30,507][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 20:37:30,574][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 21:02:51,114][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 21:02:51,208][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 21:35:16,350][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 21:35:16,465][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 21:35:30,510][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 21:35:30,605][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 21:52:40,323][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-15 21:52:41,293][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 21:52:41,451][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 21:53:20,431][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 21:53:20,513][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 21:54:26,989][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-15 21:54:42,816][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-15 21:55:36,895][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-16 10:53:24,881][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:17:50,167][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 11:19:43,407][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-16 11:19:43,930][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 11:19:49,621][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-16 11:19:50,130][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 11:20:05,081][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:20:05,205][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 11:21:23,150][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:21:23,227][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 11:24:46,303][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-16 11:24:46,835][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 11:24:49,191][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-16 11:24:49,704][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 11:25:04,896][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:25:04,982][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 11:26:52,632][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:26:52,707][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 11:27:19,409][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:27:19,502][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 11:30:34,342][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-16 11:30:34,868][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 11:30:37,234][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:30:37,331][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[ERROR][2020-08-16 11:30:43,208][log.py:222]Internal Server Error: /uploadimg
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view article.views.uploadImg didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-16 11:32:27,359][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:32:32,964][log.py:222]Internal Server Error: /uploadimg
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view article.views.uploadImg didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-16 11:34:28,516][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 11:34:36,977][log.py:222]Internal Server Error: /uploadimg
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view article.views.uploadImg didn't return an HttpResponse object. It returned None instead.
[ERROR][2020-08-16 11:40:03,721][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 18:42:09,313][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 18:42:09,705][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 18:43:27,508][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[INFO][2020-08-16 20:09:20,801][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 20:09:40,592][log.py:222]Internal Server Error: /uploadimg
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view article.views.uploadImg didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-16 20:09:48,471][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-16 20:09:48,961][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:10:40,772][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-16 20:10:41,243][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:11:05,734][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 20:11:17,097][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 20:12:51,278][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 20:12:51,347][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 20:12:58,826][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[INFO][2020-08-16 20:13:01,747][views.py:11]Accessed /article-4/ with showArticlePage
[INFO][2020-08-16 20:14:04,006][views.py:11]Accessed /article-4/ with showArticlePage
[INFO][2020-08-16 20:14:15,084][views.py:47]Accessed /post-article?fid=1 with showWriteArticlePage
[ERROR][2020-08-16 20:14:15,147][log.py:222]Internal Server Error: /static/wangEditor.min.js.map
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 108, in showBin
    logger.error(f'Accessed {request.get_full_path()} with showBin matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-16 20:14:21,269][views.py:62]Accessed /list-article?fid=2 with showArticlePage
[INFO][2020-08-16 20:14:22,270][views.py:32]Accessed /info with showInfo
[INFO][2020-08-16 20:14:22,851][views.py:62]Accessed /list-article?fid=2 with showArticlePage
[INFO][2020-08-16 20:14:23,262][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[INFO][2020-08-16 20:14:23,589][views.py:32]Accessed /info with showInfo
[INFO][2020-08-16 20:14:24,305][views.py:62]Accessed /list-article?fid=2 with showArticlePage
[INFO][2020-08-16 20:14:24,862][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[INFO][2020-08-16 20:16:09,187][views.py:32]Accessed /info with showInfo
[INFO][2020-08-16 20:18:53,166][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:18:53,612][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:19:29,918][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:19:30,458][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:19:54,696][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:19:55,254][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:20:03,098][autoreload.py:222]D:\Project\webinfo\webinfo\urls.py changed, reloading.
[INFO][2020-08-16 20:20:03,549][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:20:14,666][autoreload.py:222]D:\Project\webinfo\webinfo\urls.py changed, reloading.
[INFO][2020-08-16 20:20:15,127][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:20:24,027][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:20:24,482][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:20:27,923][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:20:28,380][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:20:30,705][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:20:31,205][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:20:45,627][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:20:46,087][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:20:50,591][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:20:51,038][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:21:30,585][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-16 20:21:33,519][log.py:222]Internal Server Error: /login_admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 74, in showLoginAdmin
    if request.session["admin"]:
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\sessions\backends\base.py", line 64, in __getitem__
    return self._session[key]
KeyError: 'admin'
[INFO][2020-08-16 20:21:49,458][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:21:49,944][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:24:19,455][autoreload.py:222]D:\Project\webinfo\webinfo\urls.py changed, reloading.
[INFO][2020-08-16 20:24:20,048][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:25:01,801][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:25:02,249][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:25:08,920][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:25:09,365][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:25:12,757][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:25:13,208][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:25:53,866][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:25:54,319][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:26:40,535][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:26:40,980][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:26:46,615][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:26:47,069][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:28:38,976][autoreload.py:222]D:\Project\webinfo\main\models.py changed, reloading.
[INFO][2020-08-16 20:28:39,439][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:29:25,586][autoreload.py:222]D:\Project\webinfo\main\models.py changed, reloading.
[INFO][2020-08-16 20:29:26,027][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:30:58,200][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:30:58,783][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:31:32,900][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:31:33,346][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:31:51,024][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:31:51,478][autoreload.py:598]Watching for file changes with StatReloader
[WARNING][2020-08-16 20:32:00,864][log.py:222]Not Found: /admin/
[INFO][2020-08-16 20:33:45,801][autoreload.py:222]D:\Project\webinfo\main\admin.py changed, reloading.
[INFO][2020-08-16 20:33:46,264][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:34:15,984][autoreload.py:222]D:\Project\webinfo\main\admin.py changed, reloading.
[INFO][2020-08-16 20:34:16,462][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-16 20:34:21,765][log.py:222]Internal Server Error: /django$$admin/main/settingsmodel/
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main_settingsmodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\options.py", line 728, in get_changelist_instance
    return ChangeList(
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\views\main.py", line 98, in __init__
    self.get_results(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\views\main.py", line 226, in get_results
    result_count = paginator.count
  File "C:\Program Files (x86)\Python\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\paginator.py", line 91, in count
    return c()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\query.py", line 397, in count
    return self.query.get_count(using=self.db)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\sql\query.py", line 518, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\sql\query.py", line 503, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main_settingsmodel
[INFO][2020-08-16 20:34:51,243][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:35:13,393][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:35:14,145][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-16 20:36:22,026][log.py:222]Internal Server Error: /dologin_admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 103, in doLoginAdmin
    if password and SettingsModel.objects.get('adminpassword').sValue==password:
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\query.py", line 404, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\sql\query.py", line 1248, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
[INFO][2020-08-16 20:37:11,719][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:37:12,167][autoreload.py:598]Watching for file changes with StatReloader
[WARNING][2020-08-16 20:37:14,343][log.py:222]Not Found: /admin
[INFO][2020-08-16 20:50:28,877][autoreload.py:222]D:\Project\webinfo\webinfo\urls.py changed, reloading.
[INFO][2020-08-16 20:50:29,450][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:50:52,574][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:50:53,031][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:51:16,150][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:51:16,628][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-16 20:51:16,979][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.showAdmin didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-16 20:51:18,969][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:51:19,446][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-16 20:51:20,330][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.showAdmin didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-16 20:51:31,643][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:51:32,090][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:51:33,332][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:51:33,817][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:51:36,169][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:51:36,622][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-16 20:51:37,855][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:51:38,319][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-16 20:51:38,777][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 115, in showAdmin
    'alert': alert,
NameError: name 'alert' is not defined
[INFO][2020-08-16 20:51:43,938][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-16 20:51:44,409][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 10:03:32,916][autoreload.py:598]Watching for file changes with StatReloader
[WARNING][2020-08-17 10:03:34,477][log.py:222]Not Found: /admin/
[WARNING][2020-08-17 10:03:34,525][log.py:222]Not Found: /favicon.ico
[INFO][2020-08-17 10:58:44,778][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 10:58:45,260][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 11:00:08,769][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 11:00:09,512][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 11:00:23,933][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 11:00:24,395][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 12:34:27,802][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 113, in showAdmin
    template = loader.get_template('admin.html')
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 482, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 543, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 169: 'for'. Looking for one of: empty, endfor.
[INFO][2020-08-17 12:37:25,776][views.py:62]Accessed /list-article?fid=1 with showArticlePage
[INFO][2020-08-17 12:37:54,299][views.py:11]Accessed /article-4/ with showArticlePage
[INFO][2020-08-17 12:42:19,152][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 12:43:05,381][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 12:43:05,840][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 12:43:23,555][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 12:43:24,029][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:01:24,226][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:01:36,371][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:01:36,830][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:01:43,503][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:01:43,981][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 15:04:59,291][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-17 15:05:32,796][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:05:33,267][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:05:35,570][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:05:36,056][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:06:37,646][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:06:38,121][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 15:06:43,789][views.py:154]Exception at doAdminAction: name 'time' is not defined
[ERROR][2020-08-17 15:06:43,809][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-17 15:07:27,774][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:07:28,535][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 15:07:32,238][views.py:156]Exception at doAdminAction: 'NoneType' object has no attribute 'name'
[ERROR][2020-08-17 15:07:32,260][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[ERROR][2020-08-17 15:08:12,245][views.py:156]Exception at doAdminAction: 'NoneType' object has no attribute 'name'
[ERROR][2020-08-17 15:08:12,262][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[ERROR][2020-08-17 15:09:04,259][log.py:222]Internal Server Error: /s/filename
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 211, in showImages
    logger.error(f'Accessed {request.get_full_path()} with showImages matched nothing.' % path)
TypeError: not all arguments converted during string formatting
[INFO][2020-08-17 15:09:31,915][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:09:32,394][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:15:02,496][views.py:13]Accessed / with showHome
[INFO][2020-08-17 15:21:26,754][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:21:27,221][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:21:57,023][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:21:57,512][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 15:22:08,663][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:22:09,228][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 15:22:10,912][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 113, in showAdmin
    template = loader.get_template('admin.html')
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 448, in parse
    raise self.error(token, e)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 446, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 562, in compile_filter
    return FilterExpression(token, self)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\template\base.py", line 661, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '-text' from 'main-text'
[ERROR][2020-08-17 15:22:22,793][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 123, in showAdmin
    main_text = SettingsModel.objects.filter(key='main-text').sValue
AttributeError: 'QuerySet' object has no attribute 'sValue'
[INFO][2020-08-17 15:22:37,970][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:22:38,438][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 15:23:17,441][views.py:164]Exception at doAdminAction: name 'SettingModel' is not defined
[ERROR][2020-08-17 15:23:17,460][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-17 15:23:36,826][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 15:23:37,313][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:00:54,337][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:00:54,849][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:01:24,667][autoreload.py:222]D:\Project\webinfo\main\models.py changed, reloading.
[INFO][2020-08-17 16:01:25,373][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:01:37,756][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:04:11,565][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:04:12,020][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:04:38,497][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:04:38,972][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:04:47,837][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:04:48,278][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:07:04,314][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:07:04,764][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:18:29,470][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:18:29,946][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:19:51,320][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:19:51,791][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:21:26,324][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:21:26,833][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:21:34,674][autoreload.py:222]D:\Project\webinfo\main\models.py changed, reloading.
[INFO][2020-08-17 16:21:35,152][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:21:42,946][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 16:22:18,545][views.py:178]Exception at doAdminAction: string indices must be integers
[ERROR][2020-08-17 16:22:18,563][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-17 16:26:04,054][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 16:26:04,434][views.py:178]Exception at doAdminAction: <traceback object at 0x000001A3A4215F80>
[ERROR][2020-08-17 16:26:04,454][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-17 16:26:29,514][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:26:29,994][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 16:26:32,680][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Project\webinfo\main\views.py", line 173, in doAdminAction
    User.objects.create_user(username=username, password=password)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\auth\models.py", line 147, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\auth\models.py", line 141, in _create_user
    user.save(using=self._db)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\base.py", line 782, in save_base
    updated = self._save_table(
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\base.py", line 924, in _do_insert
    return manager._insert(
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\sql\compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 178, in doAdminAction
    logger.error('Exception at doAdminAction: '+str(e.__traceback__()))
TypeError: 'traceback' object is not callable
[INFO][2020-08-17 16:26:45,554][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:26:46,040][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 16:27:44,686][views.py:178]Exception at doAdminAction: <traceback object at 0x000002450149D2C0>
[ERROR][2020-08-17 16:27:44,706][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-17 16:27:56,461][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:27:56,901][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 16:28:50,636][views.py:178]Exception at doAdminAction: UNIQUE constraint failed: auth_user.username
[ERROR][2020-08-17 16:28:50,656][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[ERROR][2020-08-17 16:29:45,207][views.py:178]Exception at doAdminAction: string indices must be integers
[ERROR][2020-08-17 16:29:45,223][log.py:222]Internal Server Error: /admin_action
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view main.views.doAdminAction didn't return an HttpResponse object. It returned None instead.
[INFO][2020-08-17 16:41:16,101][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 16:41:28,536][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 132, in showAdmin
    'last_login_date': (User.objects.get(username=_.username)).last_login.strftime("%x"),
AttributeError: 'NoneType' object has no attribute 'strftime'
[ERROR][2020-08-17 16:42:09,994][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 132, in showAdmin
    'last_login_date': (User.objects.get(username=_.username)).last_login.strftime("%x"),
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\db\models\query.py", line 415, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
[INFO][2020-08-17 16:43:33,654][autoreload.py:222]D:\Project\webinfo\main\admin.py changed, reloading.
[INFO][2020-08-17 16:43:34,131][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:43:38,400][autoreload.py:222]D:\Project\webinfo\main\admin.py changed, reloading.
[INFO][2020-08-17 16:43:38,848][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:44:15,322][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:44:15,776][autoreload.py:598]Watching for file changes with StatReloader
[ERROR][2020-08-17 16:44:29,330][log.py:222]Internal Server Error: /admin
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\main\views.py", line 132, in showAdmin
    'last_login_date': (User.objects.get(username=_.username)).last_login.strftime("%x"),
AttributeError: 'NoneType' object has no attribute 'strftime'
[INFO][2020-08-17 16:46:12,468][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:46:12,959][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:46:26,267][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:46:26,712][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:46:48,887][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:46:49,515][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:47:43,563][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:47:44,012][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:47:48,570][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:47:49,021][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:48:05,623][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:48:06,110][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:48:18,366][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:48:18,805][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 16:48:53,003][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 16:48:53,441][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:27:25,740][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 17:27:26,188][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:28:04,872][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 17:28:05,339][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:29:55,255][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 17:29:55,701][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:31:22,061][views.py:14]Accessed / with showHome
[INFO][2020-08-17 17:31:22,910][views.py:52]Accessed /login_ with showLogin
[INFO][2020-08-17 17:31:28,715][views.py:85]Accessed /dologin?hashcode=5328f58ffb2425b2749701f281cbf21f9b776417f06cc35ba4511861a1cc0670&username=%E6%9D%8E%E5%9B%9B&password=22621454 with doLogin
[INFO][2020-08-17 17:31:28,812][views.py:14]Accessed / with showHome
[INFO][2020-08-17 17:32:31,062][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 17:32:31,508][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:40:01,152][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 17:40:01,638][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:41:04,477][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 17:41:04,957][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:41:17,194][autoreload.py:222]D:\Project\webinfo\main\views.py changed, reloading.
[INFO][2020-08-17 17:41:17,663][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 17:45:00,958][views.py:14]Accessed / with showHome
[INFO][2020-08-17 17:46:33,279][views.py:14]Accessed / with showHome
[INFO][2020-08-17 17:46:46,384][views.py:14]Accessed / with showHome
[INFO][2020-08-17 17:46:58,773][views.py:62]Accessed /list-article?fid=3 with showArticlePage
[INFO][2020-08-17 17:47:00,112][views.py:62]Accessed /list-article?fid=5 with showArticlePage
[INFO][2020-08-17 17:47:00,835][views.py:62]Accessed /list-article?fid=6 with showArticlePage
[INFO][2020-08-17 17:47:01,366][views.py:62]Accessed /list-article?fid=7 with showArticlePage
[INFO][2020-08-17 17:47:01,918][views.py:33]Accessed /info with showInfo
[INFO][2020-08-17 17:47:03,228][views.py:62]Accessed /list-article?fid=5 with showArticlePage
[INFO][2020-08-17 17:47:03,773][views.py:62]Accessed /list-article?fid=4 with showArticlePage
[INFO][2020-08-17 17:47:10,228][views.py:62]Accessed /list-article?fid=5 with showArticlePage
[INFO][2020-08-17 17:48:47,249][views.py:62]Accessed /list-article?fid=5 with showArticlePage
[INFO][2020-08-17 17:48:48,188][views.py:62]Accessed /list-article?fid=5 with showArticlePage
[INFO][2020-08-17 17:49:00,362][views.py:62]Accessed /list-article?fid=5 with showArticlePage
[INFO][2020-08-17 17:49:07,221][views.py:62]Accessed /list-article?fid=6 with showArticlePage
[INFO][2020-08-17 17:49:07,871][views.py:62]Accessed /list-article?fid=5 with showArticlePage
[INFO][2020-08-17 17:49:08,895][views.py:62]Accessed /list-article?fid=4 with showArticlePage
[INFO][2020-08-17 17:49:09,480][views.py:62]Accessed /list-article?fid=3 with showArticlePage
[INFO][2020-08-17 17:50:03,653][views.py:62]Accessed /list-article?fid=4 with showArticlePage
[INFO][2020-08-17 17:50:04,472][views.py:62]Accessed /list-article?fid=3 with showArticlePage
[INFO][2020-08-17 17:50:18,579][views.py:47]Accessed /post-article?fid=3 with showWriteArticlePage
[INFO][2020-08-17 17:51:16,076][views.py:11]Accessed /article-5/ with showArticlePage
[INFO][2020-08-17 17:57:11,122][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 17:57:11,899][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:04:45,825][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:04:46,307][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:04:49,694][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:04:50,178][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:05:13,428][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:05:13,915][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:08:27,795][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:08:28,296][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:09:00,377][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:09:00,888][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:09:27,493][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:09:28,002][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:11:07,289][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:11:07,764][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:11:11,213][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:11:11,690][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:11:21,737][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:11:22,232][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:16:37,107][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:16:37,612][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:27:35,038][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:27:35,575][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:27:47,839][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:27:48,324][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:28:05,018][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:28:05,523][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:28:26,605][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:28:27,125][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:29:35,713][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:29:36,185][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:29:44,055][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:29:44,565][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:36:55,683][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:36:56,198][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:53:39,270][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:53:39,727][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:53:40,963][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 18:53:41,470][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 18:54:01,339][autoreload.py:222]D:\Project\webinfo\webinfo\urls.py changed, reloading.
[INFO][2020-08-17 18:54:01,777][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:48:28,036][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:48:28,505][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:50:36,125][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:50:36,565][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:50:42,190][views.py:11]Accessed /article-5/ with showArticlePage
[INFO][2020-08-17 19:50:44,286][views.py:67]Accessed /edit-article?fid=3&aid= with showEditArticlePage
[ERROR][2020-08-17 19:50:44,310][log.py:222]Internal Server Error: /edit-article
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\webinfo\article\views.py", line 71, in showEditArticlePage
    article_id = int(request.GET.get('aid'))
ValueError: invalid literal for int() with base 10: ''
[INFO][2020-08-17 19:51:05,368][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:51:05,838][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:51:31,192][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:51:31,916][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:51:37,198][views.py:11]Accessed /article-5/ with showArticlePage
[INFO][2020-08-17 19:52:10,889][views.py:11]Accessed /article-5/ with showArticlePage
[INFO][2020-08-17 19:52:12,424][views.py:67]Accessed /edit-article?fid=3&aid=5 with showEditArticlePage
[INFO][2020-08-17 19:52:23,920][views.py:11]Accessed /article-6/ with showArticlePage
[INFO][2020-08-17 19:53:15,346][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:53:15,810][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:53:25,784][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:53:26,216][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:53:31,821][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:53:32,270][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:53:41,215][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:53:41,683][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:54:46,777][views.py:11]Accessed /article-6/ with showArticlePage
[INFO][2020-08-17 19:54:48,385][views.py:11]Accessed /article-6/ with showArticlePage
[INFO][2020-08-17 19:55:09,717][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:55:10,192][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:55:12,778][views.py:14]Accessed / with showHome
[INFO][2020-08-17 19:55:15,896][views.py:33]Accessed /info with showInfo
[INFO][2020-08-17 19:55:17,168][views.py:96]Accessed /list-article?fid=3 with showArticlePage
[INFO][2020-08-17 19:55:18,131][views.py:14]Accessed / with showHome
[INFO][2020-08-17 19:55:19,469][views.py:33]Accessed /info with showInfo
[INFO][2020-08-17 19:55:20,204][views.py:96]Accessed /list-article?fid=3 with showArticlePage
[INFO][2020-08-17 19:55:21,177][views.py:11]Accessed /article-6/ with showArticlePage
[INFO][2020-08-17 19:55:24,128][views.py:11]Accessed /article-5/ with showArticlePage
[INFO][2020-08-17 19:55:26,505][views.py:11]Accessed /article-6/ with showArticlePage
[INFO][2020-08-17 19:55:28,462][views.py:11]Accessed /article-5/ with showArticlePage
[INFO][2020-08-17 19:55:41,235][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:55:41,725][autoreload.py:598]Watching for file changes with StatReloader
[INFO][2020-08-17 19:55:43,507][views.py:72]Accessed /edit-article?fid=3&aid=5 with showEditArticlePage
[INFO][2020-08-17 19:55:50,499][views.py:11]Accessed /article-6/ with showArticlePage
[INFO][2020-08-17 19:55:52,784][views.py:72]Accessed /edit-article?fid=3&aid=6 with showEditArticlePage
[INFO][2020-08-17 19:56:10,882][views.py:11]Accessed /article-7/ with showArticlePage
[INFO][2020-08-17 19:56:13,321][views.py:96]Accessed /list-article?fid=3 with showArticlePage
[INFO][2020-08-17 19:56:30,338][autoreload.py:222]D:\Project\webinfo\article\views.py changed, reloading.
[INFO][2020-08-17 19:56:30,807][autoreload.py:598]Watching for file changes with StatReloader
